### ISSUE TITLE
(wrong-type-argument stringp nil)

### ISSUE THREAD

**Issue by rpodgorny** [clojure-emacs/inf-clojure#178]
## Expected behavior

working inf-clojure mode

## Actual behavior

getting `(wrong-type-argument stringp nil)` on load and `Error running timer 'auto-revert-buffers (wrong-type-argument string nil)` after that

## Steps to reproduce the problem

1) load any .clj file
2) M-x inf-clojure
3) select any repl (tried with bb and clojure)

### inf-clojure version information

inf-clojure 20200425.1648

### Lein/Boot version

n/a

### Emacs version

emacs 26.3

### Operating system

arch linux

**Comment by dpsutton** [comment]
hi @rpodgorny thanks for the report. I'm not sure how to recreate it. do you think you could `m-x toggle-debug-on-error` and get a bit more context? seems to be largely "doesn't work" but it does work for me. I want to help get this solved though.

**Comment by rpodgorny** [comment]
on load:

```Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  file-accessible-directory-p(nil)
  comint-exec-1("inf-clojure" #<buffer *inf-clojure*> "clojure" nil)
  comint-exec(#<buffer *inf-clojure*> "inf-clojure" "clojure" nil nil)
  make-comint-in-buffer("inf-clojure" nil "clojure" nil)
  apply(make-comint-in-buffer "inf-clojure" nil "clojure" nil nil)
  make-comint("inf-clojure" "clojure" nil)
  apply(make-comint "inf-clojure" "clojure" nil nil)
  inf-clojure("clojure")
  funcall-interactively(inf-clojure "clojure")
  call-interactively(inf-clojure record nil)
  command-execute(inf-clojure record)
  helm-M-x-execute-command(inf-clojure)
...
```

on timer:

```Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  expand-file-name(nil)
  auto-revert-notify-add-watch()
  auto-revert-buffers()
  apply(auto-revert-buffers nil)
  timer-event-handler([t 24249 29311 706185 5 auto-revert-buffers nil nil 412000])
```

**Comment by dpsutton** [comment]
@rpodgorny can you verify that clojure is on the path visible to emacs? The best guess that I have now is that emacs can't see the program `clojure` and its not checking that until it gets deep into comint.

`(shell-command-to-string "which clojure")` or `m-x eshell` and type `which clojure` should let you know. I'm guessing this is your problem and what the nil error is.

**Comment by rpodgorny** [comment]
unfortunately, this does not seem to be the case:

```
Welcome to the Emacs shell

~/tmp/ipfshot $ which clojure
/usr/bin/clojure
```

**Comment by mcphailm** [comment]
I am also encountering this. I believe it happens when inf-clojure is run in a directory that does not contain a clojure project.

clojure-project-dir seems to return nil when not in a clojure project directory.

This seems to fix the problem. The change is in the line:
      (let ((default-directory (or (clojure-project-dir) "./"))

(defun inf-clojure (cmd)
  "Run an inferior Clojure process, input and output via buffer `*inf-clojure*'.
If there is a process already running in `*inf-clojure*', just
switch to that buffer.

CMD is a string which serves as the startup command or a cons of
host and port.

 Prompts user for repl startup command and repl type if not
inferrable from startup command. Uses
`inf-clojure-custom-repl-type' and `inf-clojure-custom-startup'
if those are set. Use a prefix to prevent using these when they
are set.

 Runs the hooks from `inf-clojure-mode-hook' (after the
`comint-mode-hook' is run).  \(Type \\[describe-mode] in the
process buffer for a list of commands.)"
  (interactive (list (or (unless current-prefix-arg
                           inf-clojure-custom-startup)
                         (completing-read "Select Clojure REPL startup command: "
                                          (mapcar #'cdr inf-clojure-startup-forms)
                                          nil
                                          'confirm-after-completion))))
  (if (not (comint-check-proc "*inf-clojure*"))
      ;; run the new process in the project's root when in a project folder
      (let ((default-directory (or (clojure-project-dir) "./"))
            (cmdlist (if (consp cmd)
                         (list cmd)
                       (split-string cmd)))
            (repl-type (or (unless prefix-arg
                             inf-clojure-custom-repl-type)
                           (car (rassoc cmd inf-clojure-startup-forms))
                           (inf-clojure--prompt-repl-type))))
        (message "Starting Clojure REPL via `%s'..." cmd)
        (with-current-buffer (apply #'make-comint
                                    "inf-clojure" (car cmdlist) nil (cdr cmdlist))
          (inf-clojure-mode)
          (setq-local inf-clojure-repl-type repl-type)
          (hack-dir-local-variables-non-file-buffer))))
  (setq inf-clojure-buffer "*inf-clojure*")
  (if inf-clojure-repl-use-same-window
      (pop-to-buffer-same-window "*inf-clojure*")
    (pop-to-buffer "*inf-clojure*")))

**Comment by dpsutton** [comment]
@mcphailm perfect! Excellent catch. Would you like to contribute this patch? If so I would love to accept your PR and have you as a contributor. If its too much work i'm happy to make the PR myself and acknowledge you in the commit message instead.

**Comment by dpsutton** [comment]
@rpodgorny just to make sure its clear, the workaround until we get this patched is to just include an empty deps.edn file somewhere in the directory chain.

echo `{}` > deps.edn somewhere should fix it while we make a final fix.

**Comment by mcphailm** [comment]
I'll let you make the change. Thanks for your work on this.
