### ISSUE TITLE
Make it possible to turn off completions in clojure-mode buffers

### ISSUE THREAD

**Issue by martintrojer** [clojure-emacs/inf-clojure#5]
If the REPL is "busy" inf-clojure will interrupt text entry when editing text in clojure-mode buffers. Some users might not mind, some do. Would be good to be able to disable this via configuration.

Please separate this config from disabling completions in the `*inf-clojure*` buffer, which you probably always want to have turned on.

**Comment by bbatsov** [comment]
Yeah, that makes sense.

**Comment by martintrojer** [comment]
Would be happy to help if I could find out how this minor-mode completion is wired. Doesn't look like company mode to me :) Any pointer would be appreciated, if I get somewhere I'll raise a PR.

**Comment by bbatsov** [comment]
[This function](https://github.com/clojure-emacs/inf-clojure/blob/master/inf-clojure.el#L618) provides the completion in both the major and the minor mode.

**Comment by martintrojer** [comment]
The thing I can't figure out is how `inf-clojure-completion-at-point` is wired into "the completion framework", which are we using? Is this wiring different for the major and minor modes?

**Comment by bbatsov** [comment]
The wiring is done [here](https://github.com/clojure-emacs/inf-clojure/blob/master/inf-clojure.el#L130). This is actually Emacs's built-in completion mechanism and company-mode simply leverages it, so that people won't have to define company-mode specific completion commands. The wiring is exactly the same for both the major and the minor mode.

Thinking more about the issue we might try to actually check if the REPL is busy and not do the completion then. There's also one more thing to consider - if you're not using something that fetches the completions automatically (like company) this will likely never the an issue (as you're manually triggering completion with `M-TAB` or `TAB`).
