### ISSUE TITLE
Eldoc error when running boot repl

### ISSUE THREAD

**Issue by AdamFrey** [clojure-emacs/inf-clojure#79]
## Expected behavior
Creates a usable inf-clojure repl using `boot repl`
## Actual behavior
An eldoc error is thrown constantly while typing in the repl
```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  string-match("\\Ca*true\\Ca*" nil nil)
  #[257 "\301\302\303\304#)\207" [inhibit-changing-match-data "\\Ca*true\\Ca*" nil t string-match] 8 "\n\n(fn STRING)"](nil)
  inf-clojure--response-match-p("(js/global.hasOwnProperty \"$$LUMO_GLOBALS\")" #[257 "\301\302\303\304#)\207" [inhibit-changing-match-data "\\Ca*true\\Ca*" nil t string-match] 8 "\n\n(fn STRING)"] #<process inf-clojure<1>>)
  apply(inf-clojure--response-match-p ("(js/global.hasOwnProperty \"$$LUMO_GLOBALS\")" #[257 "\301\302\303\304#)\207" [inhibit-changing-match-data "\\Ca*true\\Ca*" nil t string-match] 8 "\n\n(fn STRING)"] #<process inf-clojure<1>>))
  inf-clojure--lumo-p(#<process inf-clojure<1>>)
  inf-clojure--detect-repl-type(#<process inf-clojure<1>>)
  inf-clojure--set-repl-type(#<process inf-clojure<1>>)
  inf-clojure-arglists-form()
  inf-clojure-arglists("nREPL")
  inf-clojure-eldoc-arglists(#("nREPL" 0 5 (fontified t face clojure-interop-method-face front-sticky (field inhibit-line-move-field-capture) rear-nonsticky t field output inhibit-line-move-field-capture t)))
  inf-clojure-eldoc()
  eldoc-print-current-symbol-info()
  #[0 "\204    \205\n\303>?\205\304 \207" [eldoc-mode global-eldoc-mode eldoc-documentation-function (nil ignore) eldoc-print-current-symbol-info] 2]()
  apply(#[0 "\204    \205\n\303>?\205\304 \207" [eldoc-mode global-eldoc-mode eldoc-documentation-function (nil ignore) eldoc-print-current-symbol-info] 2] nil)
  timer-event-handler([t 0 0 500000 nil #[0 "\204    \205\n\303>?\205\304 \207" [eldoc-mode global-eldoc-mode eldoc-documentation-function (nil ignore) eldoc-print-current-symbol-info] 2] nil idle 0])
```
## Steps to reproduce the problem
Create an inf-clojure repl buffer with `boot repl`

### inf-clojure version information
20170520.914
### Lein/Boot version
2.7.1
### Emacs version
25.5.1

### Operating system
Ubuntu 17.04

**Comment by arichiardi** [comment]
Ok so new Emacs here, I have not checked 25.1 sorry but I will try to reproduce with 24.5.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by arichiardi** [comment]
This has nothing to do with the emacs version, but basically involves the repl type detection. The first we try is `lumo`, but this fails because the normal Clojure `nrepl` does not of course has `js/` in its namespaces.
I will need to add in first place code for detection `nrepl` and then if it is not that, try all the others. In this way we are sure to rule out attempts that cause evaluation failures like this. @bbatsov

**Comment by bbatsov** [comment]
> I will need to add in first place code for detection nrepl and then if it is not that, try all the others. In this way we are sure to rule out attempts that cause evaluation failures like this. @bbatsov

There's not such thing as nREPL here - that's actually REPLy (which uses nREPL internally, but `inf-clojure` can't really leverage nREpL directly so it shouldn't care about this). I REPLy repl should be treated as a regular Clojure REPL. Btw, `lein` and `boot` start exactly the same repl, so I'm pretty confused why this works with `lein`, but not with `boot`.

**Comment by bbatsov** [comment]
> This has nothing to do with the emacs version, but basically involves the repl type detection. The first we try is lumo, but this fails because the normal Clojure nrepl does not of course has js/ in its namespaces.

On a related note - shouldn't there also be some REPL type detected in the end regardless what was checked first? Seems that's the real issue here.

**Comment by arichiardi** [comment]
Yes, there is a default `case` of course - we always default to a Clojure Repl. The problem is that the code for detecting the other repl types is failing in the Clojure Repl because is relying on `js/`.
I will try to find a better way, maybe I should ping Lumo and Plank for a clj-compliant way.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by bbatsov** [comment]
I guess they can simply add some var similar to `*clojure-version*` to simplify the process.

**Comment by arichiardi** [comment]
As per discussion in linked PR, the issue is not as easy as it seems because there is no common way to detect a Repl type at the moment and folks maintening them are not willing to compromise at the moment.
So my workaround would be to kind of detect and skip the inevitable error we will receive (js/ is not defined in nrepl for instance) and return a false in the detection function.

**Comment by arichiardi** [comment]
Another problem I found is related to the Ansi code the repls are sending. The `read` function fails and throws an error. I can ignore that for now but I need to get rid of the ansi codes somehow or nothing is readable otherwise. Lumo does not have this problem because we are using it in dumb mode.

**Comment by arichiardi** [comment]
I found a package that does the ANSI filtering. This is the [commit](https://github.com/chumpage/ack-menu/commit/ef5d868427554c09c86f3802447204f77b7fd41a) to take inspiration from.

**Comment by arichiardi** [comment]
The error should be solved with the Caveat added to not use colors for now: `boot repl -C` is now used by `inf-clojure`
